import { ApiProperty } from '@nestjs/swagger';
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Index,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  BaseEntity,
  Entity,
} from 'typeorm';

@Entity('users_roles')
export class UsersRoles extends BaseEntity {
  @ApiProperty({
    description: 'autogenerated id for the user',
    example: 1,
  })
  @PrimaryGeneratedColumn()
  id_role: number;

  @ApiProperty({
    description: 'login for the user',
    example: 'joseantoniobg',
  })
  @Index('ix_key', { unique: true })
  @Column({ type: 'varchar', length: 50 })
  unique_key: string;

  @ApiProperty({
    description: 'the role description',
    example: 'user can edit orders',
  })
  @Column({ type: 'varchar', length: 200 })
  description: string;

  @ApiProperty({
    description: 'readable description for the role',
    example: 1,
  })
  @ApiProperty({
    description: 'timestamp when the user was created',
  })
  @CreateDateColumn({ type: 'timestamp with time zone' })
  created_at: Date;

  @ApiProperty({
    description: 'timestamp when the user was last updated',
  })
  @UpdateDateColumn({ type: 'timestamp with time zone' })
  updated_at: Date;

  @ApiProperty({
    description: 'timestamp when the user was deleted',
    required: false,
  })
  @DeleteDateColumn({ type: 'timestamp with time zone' })
  deleted_at: Date;
}
